/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Forge Maestro API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */
import type {
  GetApiV1GenerationsParams,
  GithubComComfyCreatorsCreatorBackendInternalDomainGeneration,
  GithubComComfyCreatorsCreatorBackendInternalServiceGenerationGenerationResult,
  InternalApiHandlerBatchResponse,
  InternalApiHandlerGenerateRequest,
  InternalApiHandlerGenerateResponse
} from '../models';

import { api } from '../../lib/api';
import type { BodyType } from '../../lib/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Returns batch progress counters and the full list of its generations.
 * @summary Get Batch
 */
export const getApiV1BatchesId = (
    id: string,
 options?: SecondParameter<typeof api<InternalApiHandlerBatchResponse>>,) => {
      return api<InternalApiHandlerBatchResponse>(
      {url: `/api/v1/batches/${id}`, method: 'GET'
    },
      options);
    }
  /**
 * Returns all generations belonging to the given batch.
 * @summary List Batch Generations
 */
export const getApiV1BatchesIdGenerations = (
    id: string,
 options?: SecondParameter<typeof api<GithubComComfyCreatorsCreatorBackendInternalDomainGeneration[]>>,) => {
      return api<GithubComComfyCreatorsCreatorBackendInternalDomainGeneration[]>(
      {url: `/api/v1/batches/${id}/generations`, method: 'GET'
    },
      options);
    }
  /**
 * Creates a batch of ComfyUI generations and enqueues them for processing.
 * @summary Create Generation Batch
 */
export const postApiV1Generate = (
    internalApiHandlerGenerateRequest: BodyType<InternalApiHandlerGenerateRequest>,
 options?: SecondParameter<typeof api<InternalApiHandlerGenerateResponse>>,) => {
      return api<InternalApiHandlerGenerateResponse>(
      {url: `/api/v1/generate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: internalApiHandlerGenerateRequest
    },
      options);
    }
  /**
 * Returns the most recent generations for the authenticated user. Use ?limit= to control count (max 100, default 20).
 * @summary List Generations
 */
export const getApiV1Generations = (
    params?: GetApiV1GenerationsParams,
 options?: SecondParameter<typeof api<GithubComComfyCreatorsCreatorBackendInternalServiceGenerationGenerationResult[]>>,) => {
      return api<GithubComComfyCreatorsCreatorBackendInternalServiceGenerationGenerationResult[]>(
      {url: `/api/v1/generations`, method: 'GET',
        params
    },
      options);
    }
  /**
 * Retrieves the status of a specific generation and its result if completed.
 * @summary Get Generation Status
 */
export const getApiV1GenerationsId = (
    id: string,
 options?: SecondParameter<typeof api<GithubComComfyCreatorsCreatorBackendInternalServiceGenerationGenerationResult>>,) => {
      return api<GithubComComfyCreatorsCreatorBackendInternalServiceGenerationGenerationResult>(
      {url: `/api/v1/generations/${id}`, method: 'GET'
    },
      options);
    }
  export type GetApiV1BatchesIdResult = NonNullable<Awaited<ReturnType<typeof getApiV1BatchesId>>>
export type GetApiV1BatchesIdGenerationsResult = NonNullable<Awaited<ReturnType<typeof getApiV1BatchesIdGenerations>>>
export type PostApiV1GenerateResult = NonNullable<Awaited<ReturnType<typeof postApiV1Generate>>>
export type GetApiV1GenerationsResult = NonNullable<Awaited<ReturnType<typeof getApiV1Generations>>>
export type GetApiV1GenerationsIdResult = NonNullable<Awaited<ReturnType<typeof getApiV1GenerationsId>>>
