/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Forge Maestro API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * Returns batch progress counters and the full list of its generations.
 * @summary Get Batch
 */
export const GetApiV1BatchesIdParams = zod.object({
  "id": zod.string().describe('Batch ID')
})

export const GetApiV1BatchesIdResponse = zod.object({
  "batch": zod.object({
  "completed_at": zod.string().optional(),
  "completed_generations": zod.number().optional(),
  "created_at": zod.string().optional(),
  "failed_generations": zod.number().optional(),
  "id": zod.string().optional(),
  "priority": zod.enum(['urgent', 'standard', 'patient']).optional(),
  "status": zod.enum(['pending', 'running', 'completed', 'partial_failure', 'failed']).optional(),
  "total_generations": zod.number().optional(),
  "user_id": zod.string().optional()
}).optional(),
  "generations": zod.array(zod.object({
  "attachments": zod.array(zod.object({
  "type": zod.string().optional(),
  "url": zod.string().optional()
})).optional().describe('Ignored by DB, handled manually via JSONB byte mapping in Repo.'),
  "batch_id": zod.string().optional(),
  "comfy_workflow": zod.looseObject({

}).optional().describe('Ignored by DB, handled manually via JSONB byte mapping in Repo.'),
  "credit_cost": zod.number().optional(),
  "enqueued_at": zod.string().optional(),
  "error_log": zod.string().optional(),
  "fault_source": zod.enum(['user', 'platform']).optional(),
  "finished_at": zod.string().optional().describe('A better name than completed at, because we\'ll also need to track when did the job fail incase it fail'),
  "id": zod.string().optional(),
  "instance_id": zod.string().optional(),
  "output_expires_at": zod.string().optional(),
  "output_s3_key": zod.string().optional(),
  "priority": zod.enum(['urgent', 'standard', 'patient']).optional().describe('mapped from Batch'),
  "prompt": zod.string().optional(),
  "retry_count": zod.number().optional(),
  "started_at": zod.string().optional(),
  "status": zod.enum(['queued', 'running', 'completed', 'failed', 'retrying']).optional(),
  "user_id": zod.string().optional()
})).optional()
})

/**
 * Returns all generations belonging to the given batch.
 * @summary List Batch Generations
 */
export const GetApiV1BatchesIdGenerationsParams = zod.object({
  "id": zod.string().describe('Batch ID')
})

export const GetApiV1BatchesIdGenerationsResponseItem = zod.object({
  "attachments": zod.array(zod.object({
  "type": zod.string().optional(),
  "url": zod.string().optional()
})).optional().describe('Ignored by DB, handled manually via JSONB byte mapping in Repo.'),
  "batch_id": zod.string().optional(),
  "comfy_workflow": zod.looseObject({

}).optional().describe('Ignored by DB, handled manually via JSONB byte mapping in Repo.'),
  "credit_cost": zod.number().optional(),
  "enqueued_at": zod.string().optional(),
  "error_log": zod.string().optional(),
  "fault_source": zod.enum(['user', 'platform']).optional(),
  "finished_at": zod.string().optional().describe('A better name than completed at, because we\'ll also need to track when did the job fail incase it fail'),
  "id": zod.string().optional(),
  "instance_id": zod.string().optional(),
  "output_expires_at": zod.string().optional(),
  "output_s3_key": zod.string().optional(),
  "priority": zod.enum(['urgent', 'standard', 'patient']).optional().describe('mapped from Batch'),
  "prompt": zod.string().optional(),
  "retry_count": zod.number().optional(),
  "started_at": zod.string().optional(),
  "status": zod.enum(['queued', 'running', 'completed', 'failed', 'retrying']).optional(),
  "user_id": zod.string().optional()
})
export const GetApiV1BatchesIdGenerationsResponse = zod.array(GetApiV1BatchesIdGenerationsResponseItem)

/**
 * Creates a batch of ComfyUI generations and enqueues them for processing.
 * @summary Create Generation Batch
 */



export const PostApiV1GenerateBody = zod.object({
  "generations": zod.array(zod.object({
  "attachments": zod.array(zod.object({
  "type": zod.string().optional(),
  "url": zod.string().optional()
})).optional(),
  "comfy_workflow": zod.array(zod.number()).optional(),
  "prompt": zod.string().optional()
})).min(1),
  "priority": zod.enum(['urgent', 'standard', 'patient'])
})

/**
 * Returns the most recent generations for the authenticated user. Use ?limit= to control count (max 100, default 20).
 * @summary List Generations
 */
export const GetApiV1GenerationsQueryParams = zod.object({
  "limit": zod.number().optional().describe('Max results (default 20, max 100)')
})

export const GetApiV1GenerationsResponseItem = zod.object({
  "generation": zod.object({
  "attachments": zod.array(zod.object({
  "type": zod.string().optional(),
  "url": zod.string().optional()
})).optional().describe('Ignored by DB, handled manually via JSONB byte mapping in Repo.'),
  "batch_id": zod.string().optional(),
  "comfy_workflow": zod.looseObject({

}).optional().describe('Ignored by DB, handled manually via JSONB byte mapping in Repo.'),
  "credit_cost": zod.number().optional(),
  "enqueued_at": zod.string().optional(),
  "error_log": zod.string().optional(),
  "fault_source": zod.enum(['user', 'platform']).optional(),
  "finished_at": zod.string().optional().describe('A better name than completed at, because we\'ll also need to track when did the job fail incase it fail'),
  "id": zod.string().optional(),
  "instance_id": zod.string().optional(),
  "output_expires_at": zod.string().optional(),
  "output_s3_key": zod.string().optional(),
  "priority": zod.enum(['urgent', 'standard', 'patient']).optional().describe('mapped from Batch'),
  "prompt": zod.string().optional(),
  "retry_count": zod.number().optional(),
  "started_at": zod.string().optional(),
  "status": zod.enum(['queued', 'running', 'completed', 'failed', 'retrying']).optional(),
  "user_id": zod.string().optional()
}).optional(),
  "output_expiry": zod.string().optional(),
  "output_url": zod.string().optional()
})
export const GetApiV1GenerationsResponse = zod.array(GetApiV1GenerationsResponseItem)

/**
 * Retrieves the status of a specific generation and its result if completed.
 * @summary Get Generation Status
 */
export const GetApiV1GenerationsIdParams = zod.object({
  "id": zod.string().describe('Generation ID')
})

export const GetApiV1GenerationsIdResponse = zod.object({
  "generation": zod.object({
  "attachments": zod.array(zod.object({
  "type": zod.string().optional(),
  "url": zod.string().optional()
})).optional().describe('Ignored by DB, handled manually via JSONB byte mapping in Repo.'),
  "batch_id": zod.string().optional(),
  "comfy_workflow": zod.looseObject({

}).optional().describe('Ignored by DB, handled manually via JSONB byte mapping in Repo.'),
  "credit_cost": zod.number().optional(),
  "enqueued_at": zod.string().optional(),
  "error_log": zod.string().optional(),
  "fault_source": zod.enum(['user', 'platform']).optional(),
  "finished_at": zod.string().optional().describe('A better name than completed at, because we\'ll also need to track when did the job fail incase it fail'),
  "id": zod.string().optional(),
  "instance_id": zod.string().optional(),
  "output_expires_at": zod.string().optional(),
  "output_s3_key": zod.string().optional(),
  "priority": zod.enum(['urgent', 'standard', 'patient']).optional().describe('mapped from Batch'),
  "prompt": zod.string().optional(),
  "retry_count": zod.number().optional(),
  "started_at": zod.string().optional(),
  "status": zod.enum(['queued', 'running', 'completed', 'failed', 'retrying']).optional(),
  "user_id": zod.string().optional()
}).optional(),
  "output_expiry": zod.string().optional(),
  "output_url": zod.string().optional()
})

