/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Forge Maestro API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * Retrieves the localized user profile from the internal Postgres Shadow Table.
 * @summary Get User Profile
 */
export const GetApiV1MeResponse = zod.object({
  "avatar_url": zod.string().optional(),
  "created_at": zod.string().optional(),
  "email": zod.string().optional(),
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "updated_at": zod.string().optional()
})

/**
 * Executes an active SQL aggregation against the credit ledger to deduce the real-time billing parity.
 * @summary Get Credit Balance
 */
export const GetApiV1MeCreditsResponse = zod.record(zod.string(), zod.number())

