/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * ComfyUI Backend API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */
import type {
  GithubComComfyCreatorsCreatorBackendInternalDomainUser
} from '../models';

import { api } from '../../lib/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Retrieves the localized user profile from the internal Postgres Shadow Table.
 * @summary Get User Profile
 */
export const getApiV1Me = (

 options?: SecondParameter<typeof api<GithubComComfyCreatorsCreatorBackendInternalDomainUser>>,) => {
      return api<GithubComComfyCreatorsCreatorBackendInternalDomainUser>(
      {url: `/api/v1/me`, method: 'GET'
    },
      options);
    }
  export type GetApiV1MeResult = NonNullable<Awaited<ReturnType<typeof getApiV1Me>>>
