/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Forge Maestro API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */
import type {
  GetApiV1MeCredits200,
  GithubComComfyCreatorsCreatorBackendInternalDomainUser
} from '../models';

import { api } from '../../lib/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Retrieves the localized user profile from the internal Postgres Shadow Table.
 * @summary Get User Profile
 */
export const getApiV1Me = (

 options?: SecondParameter<typeof api<GithubComComfyCreatorsCreatorBackendInternalDomainUser>>,) => {
      return api<GithubComComfyCreatorsCreatorBackendInternalDomainUser>(
      {url: `/api/v1/me`, method: 'GET'
    },
      options);
    }
  /**
 * Executes an active SQL aggregation against the credit ledger to deduce the real-time billing parity.
 * @summary Get Credit Balance
 */
export const getApiV1MeCredits = (

 options?: SecondParameter<typeof api<GetApiV1MeCredits200>>,) => {
      return api<GetApiV1MeCredits200>(
      {url: `/api/v1/me/credits`, method: 'GET'
    },
      options);
    }
  export type GetApiV1MeResult = NonNullable<Awaited<ReturnType<typeof getApiV1Me>>>
export type GetApiV1MeCreditsResult = NonNullable<Awaited<ReturnType<typeof getApiV1MeCredits>>>
