/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Forge Maestro API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * Returns all non-dead VM records stored in the internal database, giving a full snapshot of what the system believes is running. Admin only.
 * @summary List DB Instances
 */
export const GetApiV1AdminInstancesDbResponse = zod.object({
  "count": zod.number().optional(),
  "instances": zod.array(zod.object({
  "closed_at": zod.string().optional(),
  "created_at": zod.string().optional(),
  "id": zod.string().optional(),
  "instance_type": zod.enum(['instant', 'bare_metal', 'spot', 'reserved', 'sublease']).optional(),
  "last_generation_end_time": zod.string().optional(),
  "last_heartbeat_at": zod.string().optional(),
  "load_score": zod.number().optional(),
  "provider": zod.string().optional().describe('e.g., \"vastai\", \"akash\", \"datacrunch\"'),
  "provider_instance_id": zod.string().optional(),
  "state": zod.enum(['requesting', 'provisioning', 'ogre_provisioning', 'idle', 'busy', 'recovering', 'closing', 'dead']).optional(),
  "vram_gb": zod.number().optional()
})).optional()
})

/**
 * Returns all active instances currently reported by the Mjolnir infrastructure aggregator across every provider. Admin only.
 * @summary List Live Instances (Mjolnir)
 */
export const GetApiV1AdminInstancesLiveResponse = zod.object({
  "count": zod.number().optional(),
  "instances": zod.array(zod.object({
  "created_at": zod.string().optional(),
  "details": zod.object({
  "node_count": zod.number().optional(),
  "original": zod.record(zod.string(), zod.unknown()).optional(),
  "ports": zod.record(zod.string(), zod.string()).optional()
}).optional(),
  "id": zod.string().optional(),
  "internal_ip": zod.string().optional(),
  "location": zod.string().optional(),
  "name": zod.string().optional(),
  "network": zod.string().optional(),
  "provider": zod.string().optional(),
  "public_ip": zod.string().optional(),
  "status": zod.string().optional().describe('Should map to LeaseStatus'),
  "tags": zod.array(zod.string()).optional(),
  "type": zod.enum(['instant', 'bare_metal', 'spot', 'reserved', 'sublease']).optional()
})).optional()
})

/**
 * Enqueues a provider termination task (NeedsPost=false). Kills the VM at the provider without touching the database. Admin only.
 * @summary Terminate at Provider Only
 */
export const PostApiV1AdminInstancesTerminateProviderQueryParams = zod.object({
  "provider_vm_id": zod.string().describe('Provider-side VM ID'),
  "provider": zod.string().describe('Provider name (e.g. vastai, datacrunch)')
})

/**
 * Enqueues the close-pre → terminate-at-provider → close-post pipeline for the given internal VM ID. Admin only.
 * @summary Terminate Instance (queued)
 */
export const DeleteApiV1AdminInstancesIdParams = zod.object({
  "id": zod.string().describe('Internal VM UUID')
})

/**
 * Sets the VM state to dead and records a closing timestamp in the database. Does NOT interact with the provider. Admin only.
 * @summary Force Mark VM Dead (DB only)
 */
export const PostApiV1AdminInstancesIdMarkDeadParams = zod.object({
  "id": zod.string().describe('Internal VM UUID')
})

export const PostApiV1AdminInstancesIdMarkDeadResponse = zod.record(zod.string(), zod.string())

