/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Forge Maestro API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */
import type {
  DeleteApiV1AdminInstancesId202,
  InternalApiHandlerGetActiveInstancesDbResponse,
  InternalApiHandlerGetActiveInstancesLiveResponse,
  PostApiV1AdminInstancesIdMarkDead200,
  PostApiV1AdminInstancesTerminateProvider202,
  PostApiV1AdminInstancesTerminateProviderParams
} from '../models';

import { api } from '../../lib/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Returns all non-dead VM records stored in the internal database, giving a full snapshot of what the system believes is running. Admin only.
 * @summary List DB Instances
 */
export const getApiV1AdminInstancesDb = (

 options?: SecondParameter<typeof api<InternalApiHandlerGetActiveInstancesDbResponse>>,) => {
      return api<InternalApiHandlerGetActiveInstancesDbResponse>(
      {url: `/api/v1/admin/instances/db`, method: 'GET'
    },
      options);
    }
  /**
 * Returns all active instances currently reported by the Mjolnir infrastructure aggregator across every provider. Admin only.
 * @summary List Live Instances (Mjolnir)
 */
export const getApiV1AdminInstancesLive = (

 options?: SecondParameter<typeof api<InternalApiHandlerGetActiveInstancesLiveResponse>>,) => {
      return api<InternalApiHandlerGetActiveInstancesLiveResponse>(
      {url: `/api/v1/admin/instances/live`, method: 'GET'
    },
      options);
    }
  /**
 * Enqueues a provider termination task (NeedsPost=false). Kills the VM at the provider without touching the database. Admin only.
 * @summary Terminate at Provider Only
 */
export const postApiV1AdminInstancesTerminateProvider = (
    params: PostApiV1AdminInstancesTerminateProviderParams,
 options?: SecondParameter<typeof api<PostApiV1AdminInstancesTerminateProvider202>>,) => {
      return api<PostApiV1AdminInstancesTerminateProvider202>(
      {url: `/api/v1/admin/instances/terminate-provider`, method: 'POST',
        params
    },
      options);
    }
  /**
 * Enqueues the close-pre → terminate-at-provider → close-post pipeline for the given internal VM ID. Admin only.
 * @summary Terminate Instance (queued)
 */
export const deleteApiV1AdminInstancesId = (
    id: string,
 options?: SecondParameter<typeof api<DeleteApiV1AdminInstancesId202>>,) => {
      return api<DeleteApiV1AdminInstancesId202>(
      {url: `/api/v1/admin/instances/${id}`, method: 'DELETE'
    },
      options);
    }
  /**
 * Sets the VM state to dead and records a closing timestamp in the database. Does NOT interact with the provider. Admin only.
 * @summary Force Mark VM Dead (DB only)
 */
export const postApiV1AdminInstancesIdMarkDead = (
    id: string,
 options?: SecondParameter<typeof api<PostApiV1AdminInstancesIdMarkDead200>>,) => {
      return api<PostApiV1AdminInstancesIdMarkDead200>(
      {url: `/api/v1/admin/instances/${id}/mark-dead`, method: 'POST'
    },
      options);
    }
  export type GetApiV1AdminInstancesDbResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminInstancesDb>>>
export type GetApiV1AdminInstancesLiveResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminInstancesLive>>>
export type PostApiV1AdminInstancesTerminateProviderResult = NonNullable<Awaited<ReturnType<typeof postApiV1AdminInstancesTerminateProvider>>>
export type DeleteApiV1AdminInstancesIdResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1AdminInstancesId>>>
export type PostApiV1AdminInstancesIdMarkDeadResult = NonNullable<Awaited<ReturnType<typeof postApiV1AdminInstancesIdMarkDead>>>
