/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * ComfyUI Backend API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * Returns every team where the caller has an ACTIVE membership.
 * @summary List user's teams
 */
export const GetApiV1TeamsResponseItem = zod.object({
  "archived_at": zod.string().optional(),
  "created_at": zod.string().optional(),
  "created_by_user_id": zod.string().optional(),
  "id": zod.string().optional(),
  "joined_at": zod.string().optional(),
  "name": zod.string().optional(),
  "role": zod.string().optional(),
  "slug": zod.string().optional(),
  "status": zod.string().optional(),
  "updated_at": zod.string().optional()
})
export const GetApiV1TeamsResponse = zod.array(GetApiV1TeamsResponseItem)

