/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * ComfyUI Backend API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */
import type {
  GithubComComfyCreatorsCreatorBackendInternalDomainTeamWithMembership
} from '../models';

import { api } from '../../lib/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Returns every team where the caller has an ACTIVE membership.
 * @summary List user's teams
 */
export const getApiV1Teams = (

 options?: SecondParameter<typeof api<GithubComComfyCreatorsCreatorBackendInternalDomainTeamWithMembership[]>>,) => {
      return api<GithubComComfyCreatorsCreatorBackendInternalDomainTeamWithMembership[]>(
      {url: `/api/v1/teams`, method: 'GET'
    },
      options);
    }
  export type GetApiV1TeamsResult = NonNullable<Awaited<ReturnType<typeof getApiV1Teams>>>
