/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * ComfyUI Backend API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */
import type {
  GithubComComfyCreatorsCreatorBackendInternalApiDtoCreditBalanceResponse
} from '../models';

import { api } from '../../lib/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Returns the current credit balance for the active team. The team is resolved from the X-Team-ID request header (preferred) or the team_id cookie. The caller must be an active member of that team.
 * @summary Get team credit balance
 */
export const getApiV1Credits = (

 options?: SecondParameter<typeof api<GithubComComfyCreatorsCreatorBackendInternalApiDtoCreditBalanceResponse>>,) => {
      return api<GithubComComfyCreatorsCreatorBackendInternalApiDtoCreditBalanceResponse>(
      {url: `/api/v1/credits`, method: 'GET'
    },
      options);
    }
  export type GetApiV1CreditsResult = NonNullable<Awaited<ReturnType<typeof getApiV1Credits>>>
