/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * ComfyUI Backend API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * Returns the current credit balance for the active team. The team is resolved from the X-Team-ID request header (preferred) or the team_id cookie. The caller must be an active member of that team.
 * @summary Get team credit balance
 */
export const GetApiV1CreditsHeader = zod.object({
  "X-Team-ID": zod.string().describe('Active team UUID')
})

export const GetApiV1CreditsResponse = zod.object({
  "balance": zod.number().optional(),
  "team_id": zod.string().optional()
})

