/** @format */
import { Figtree, Inter } from "next/font/google";

const interHeading = Inter({subsets:['latin'],variable:'--font-heading'});

const figtree = Figtree({subsets:['latin'],variable:'--font-sans'});


// /** @format */

// import type { Metadata } from "next";
// import { Geist, Geist_Mono, Figtree } from "next/font/google";
// import { ClerkProvider } from "@clerk/nextjs";
// import { shadcn } from "@clerk/ui/themes";
// import "./globals.css";
// import { cn } from "@/lib/utils";
// import { ReactQueryProvider } from "@/components/ReactQueryProvider";

// const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider appearance={{ theme: shadcn }}>
//       <html
//         lang="en"
//         className={cn(
//           "h-full",
//           "antialiased",
//           geistSans.variable,
//           geistMono.variable,
//           "font-sans",
//           figtree.variable,
//         )}
//       >
//         <ReactQueryProvider>
//           <body className="min-h-full flex flex-col">{children}</body>
//         </ReactQueryProvider>
//       </html>
//     </ClerkProvider>
//   );
// }
