/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * ComfyUI Backend API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */

export type GetApiV1AdminInstancesInventoryParams = {
/**
 * Provider name (e.g. vastai, datacrunch)
 */
provider?: string;
/**
 * Comma-separated instance types to filter by
 */
types?: string;
};
