/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Forge Maestro API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */

export type GithubComComfyCreatorsCreatorBackendInternalDomainBatchPriority = typeof GithubComComfyCreatorsCreatorBackendInternalDomainBatchPriority[keyof typeof GithubComComfyCreatorsCreatorBackendInternalDomainBatchPriority];


export const GithubComComfyCreatorsCreatorBackendInternalDomainBatchPriority = {
  PriorityUrgent: 'urgent',
  PriorityStandard: 'standard',
  PriorityPatient: 'patient',
} as const;
