/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * ComfyUI Backend API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */
import type { GithubComComfyCreatorsCreatorBackendInternalDomainInstance } from './githubComComfyCreatorsCreatorBackendInternalDomainInstance';

export interface GithubComComfyCreatorsCreatorBackendInternalApiDtoGetActiveInstancesDbResponse {
  count?: number;
  instances?: GithubComComfyCreatorsCreatorBackendInternalDomainInstance[];
}
