/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Forge Maestro API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */

export type GithubComComfyCreatorsCreatorBackendInternalDomainInstanceState = typeof GithubComComfyCreatorsCreatorBackendInternalDomainInstanceState[keyof typeof GithubComComfyCreatorsCreatorBackendInternalDomainInstanceState];


export const GithubComComfyCreatorsCreatorBackendInternalDomainInstanceState = {
  InstanceStateRequesting: 'requesting',
  InstanceStateProvisioning: 'provisioning',
  InstanceStateOgreProvisioning: 'ogre_provisioning',
  InstanceStateIdle: 'idle',
  InstanceStateBusy: 'busy',
  InstanceStateRecovering: 'recovering',
  InstanceStateClosing: 'closing',
  InstanceStateDead: 'dead',
} as const;
