/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * ComfyUI Backend API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */
import type { GithubComComfyCreatorsCreatorBackendInternalClientMjolnirInstanceType } from './githubComComfyCreatorsCreatorBackendInternalClientMjolnirInstanceType';
import type { GithubComComfyCreatorsCreatorBackendInternalClientMjolnirInventoryItemGpu } from './githubComComfyCreatorsCreatorBackendInternalClientMjolnirInventoryItemGpu';
import type { GithubComComfyCreatorsCreatorBackendInternalClientMjolnirInventoryItemInstance } from './githubComComfyCreatorsCreatorBackendInternalClientMjolnirInventoryItemInstance';
import type { GithubComComfyCreatorsCreatorBackendInternalClientMjolnirInventoryItemOriginal } from './githubComComfyCreatorsCreatorBackendInternalClientMjolnirInventoryItemOriginal';
import type { GithubComComfyCreatorsCreatorBackendInternalClientMjolnirInventoryItemPricePerHour } from './githubComComfyCreatorsCreatorBackendInternalClientMjolnirInventoryItemPricePerHour';
import type { GithubComComfyCreatorsCreatorBackendInternalClientMjolnirInventoryLocation } from './githubComComfyCreatorsCreatorBackendInternalClientMjolnirInventoryLocation';
import type { GithubComComfyCreatorsCreatorBackendInternalClientMjolnirProviderType } from './githubComComfyCreatorsCreatorBackendInternalClientMjolnirProviderType';

export interface GithubComComfyCreatorsCreatorBackendInternalClientMjolnirInventoryItem {
  gpu?: GithubComComfyCreatorsCreatorBackendInternalClientMjolnirInventoryItemGpu;
  instance?: GithubComComfyCreatorsCreatorBackendInternalClientMjolnirInventoryItemInstance;
  location?: GithubComComfyCreatorsCreatorBackendInternalClientMjolnirInventoryLocation;
  original?: GithubComComfyCreatorsCreatorBackendInternalClientMjolnirInventoryItemOriginal;
  price_per_hour?: GithubComComfyCreatorsCreatorBackendInternalClientMjolnirInventoryItemPricePerHour;
  provider?: GithubComComfyCreatorsCreatorBackendInternalClientMjolnirProviderType;
  ram?: string;
  storage?: string;
  type?: GithubComComfyCreatorsCreatorBackendInternalClientMjolnirInstanceType;
  vcpu?: number;
}
