/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Forge Maestro API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */
import type { GithubComComfyCreatorsCreatorBackendInternalDomainGeneration } from './githubComComfyCreatorsCreatorBackendInternalDomainGeneration';

export interface GithubComComfyCreatorsCreatorBackendInternalServiceGenerationGenerationResult {
  generation?: GithubComComfyCreatorsCreatorBackendInternalDomainGeneration;
  output_expiry?: string;
  output_url?: string;
}
