/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Forge Maestro API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */
import type { GithubComComfyCreatorsCreatorBackendInternalDomainInstanceState } from './githubComComfyCreatorsCreatorBackendInternalDomainInstanceState';
import type { GithubComComfyCreatorsCreatorBackendInternalDomainInstanceType } from './githubComComfyCreatorsCreatorBackendInternalDomainInstanceType';

export interface GithubComComfyCreatorsCreatorBackendInternalDomainInstance {
  closed_at?: string;
  created_at?: string;
  id?: string;
  instance_type?: GithubComComfyCreatorsCreatorBackendInternalDomainInstanceType;
  last_generation_end_time?: string;
  last_heartbeat_at?: string;
  load_score?: number;
  /** e.g., "vastai", "akash", "datacrunch" */
  provider?: string;
  provider_instance_id?: string;
  state?: GithubComComfyCreatorsCreatorBackendInternalDomainInstanceState;
  vram_gb?: number;
}
