/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Forge Maestro API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */

export type GithubComComfyCreatorsCreatorBackendInternalDomainInstanceType = typeof GithubComComfyCreatorsCreatorBackendInternalDomainInstanceType[keyof typeof GithubComComfyCreatorsCreatorBackendInternalDomainInstanceType];


export const GithubComComfyCreatorsCreatorBackendInternalDomainInstanceType = {
  InstanceTypeInstant: 'instant',
  InstanceTypeBareMetal: 'bare_metal',
  InstanceTypeSpot: 'spot',
  InstanceTypeReserved: 'reserved',
  InstanceTypeSublease: 'sublease',
} as const;
