/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Forge Maestro API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */

export type GithubComComfyCreatorsCreatorBackendInternalDomainGenerationStatus = typeof GithubComComfyCreatorsCreatorBackendInternalDomainGenerationStatus[keyof typeof GithubComComfyCreatorsCreatorBackendInternalDomainGenerationStatus];


export const GithubComComfyCreatorsCreatorBackendInternalDomainGenerationStatus = {
  GenerationStatusQueued: 'queued',
  GenerationStatusRunning: 'running',
  GenerationStatusCompleted: 'completed',
  GenerationStatusFailed: 'failed',
  GenerationStatusRetrying: 'retrying',
} as const;
