/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Forge Maestro API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */

export interface GithubComComfyCreatorsCreatorBackendInternalDomainUser {
  avatar_url?: string;
  created_at?: string;
  email?: string;
  id?: string;
  name?: string;
  updated_at?: string;
}
