/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Forge Maestro API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */
import type { GithubComComfyCreatorsCreatorBackendInternalDomainAttachment } from './githubComComfyCreatorsCreatorBackendInternalDomainAttachment';
import type { GithubComComfyCreatorsCreatorBackendInternalDomainBatchPriority } from './githubComComfyCreatorsCreatorBackendInternalDomainBatchPriority';
import type { GithubComComfyCreatorsCreatorBackendInternalDomainFaultSource } from './githubComComfyCreatorsCreatorBackendInternalDomainFaultSource';
import type { GithubComComfyCreatorsCreatorBackendInternalDomainGenerationComfyWorkflow } from './githubComComfyCreatorsCreatorBackendInternalDomainGenerationComfyWorkflow';
import type { GithubComComfyCreatorsCreatorBackendInternalDomainGenerationStatus } from './githubComComfyCreatorsCreatorBackendInternalDomainGenerationStatus';

export interface GithubComComfyCreatorsCreatorBackendInternalDomainGeneration {
  /** Ignored by DB, handled manually via JSONB byte mapping in Repo. */
  attachments?: GithubComComfyCreatorsCreatorBackendInternalDomainAttachment[];
  batch_id?: string;
  /** Ignored by DB, handled manually via JSONB byte mapping in Repo. */
  comfy_workflow?: GithubComComfyCreatorsCreatorBackendInternalDomainGenerationComfyWorkflow;
  credit_cost?: number;
  enqueued_at?: string;
  error_log?: string;
  fault_source?: GithubComComfyCreatorsCreatorBackendInternalDomainFaultSource;
  /** A better name than completed at, because we'll also need to track when did the job fail incase it fail */
  finished_at?: string;
  id?: string;
  instance_id?: string;
  output_expires_at?: string;
  output_s3_key?: string;
  /** mapped from Batch */
  priority?: GithubComComfyCreatorsCreatorBackendInternalDomainBatchPriority;
  prompt?: string;
  retry_count?: number;
  started_at?: string;
  status?: GithubComComfyCreatorsCreatorBackendInternalDomainGenerationStatus;
  user_id?: string;
}
