/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Forge Maestro API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */
import type { GithubComComfyCreatorsCreatorBackendInternalClientMjolnirInstanceDetailsOriginal } from './githubComComfyCreatorsCreatorBackendInternalClientMjolnirInstanceDetailsOriginal';
import type { GithubComComfyCreatorsCreatorBackendInternalClientMjolnirInstanceDetailsPorts } from './githubComComfyCreatorsCreatorBackendInternalClientMjolnirInstanceDetailsPorts';

export interface GithubComComfyCreatorsCreatorBackendInternalClientMjolnirInstanceDetails {
  node_count?: number;
  original?: GithubComComfyCreatorsCreatorBackendInternalClientMjolnirInstanceDetailsOriginal;
  ports?: GithubComComfyCreatorsCreatorBackendInternalClientMjolnirInstanceDetailsPorts;
}
