/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * ComfyUI Backend API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */

export type GithubComComfyCreatorsCreatorBackendInternalClientMjolnirProviderType = typeof GithubComComfyCreatorsCreatorBackendInternalClientMjolnirProviderType[keyof typeof GithubComComfyCreatorsCreatorBackendInternalClientMjolnirProviderType];


export const GithubComComfyCreatorsCreatorBackendInternalClientMjolnirProviderType = {
  ProviderTypeAkash: 'akash',
  ProviderTypeVoltagePark: 'voltagepark',
  ProviderTypeDataCrunch: 'datacrunch',
  ProviderTypeHotAisle: 'hotaisle',
  ProviderTypeVastAI: 'vastai',
  ProviderTypeMasseCompute: 'massecompute',
  ProviderTypeCudoCompute: 'cudocompute',
  ProviderTypeHyperstack: 'hyperstack',
  ProviderTypeVultr: 'vultr',
} as const;
