/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Forge Maestro API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */

export type GithubComComfyCreatorsCreatorBackendInternalDomainBatchStatus = typeof GithubComComfyCreatorsCreatorBackendInternalDomainBatchStatus[keyof typeof GithubComComfyCreatorsCreatorBackendInternalDomainBatchStatus];


export const GithubComComfyCreatorsCreatorBackendInternalDomainBatchStatus = {
  BatchStatusPending: 'pending',
  BatchStatusRunning: 'running',
  BatchStatusCompleted: 'completed',
  BatchStatusPartialFailure: 'partial_failure',
  BatchStatusFailed: 'failed',
} as const;
