/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Forge Maestro API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */

export type GithubComComfyCreatorsCreatorBackendInternalDomainFaultSource = typeof GithubComComfyCreatorsCreatorBackendInternalDomainFaultSource[keyof typeof GithubComComfyCreatorsCreatorBackendInternalDomainFaultSource];


export const GithubComComfyCreatorsCreatorBackendInternalDomainFaultSource = {
  FaultSourceUser: 'user',
  FaultSourcePlatform: 'platform',
} as const;
