/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Forge Maestro API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */

/**
 * Ignored by DB, handled manually via JSONB byte mapping in Repo.
 */
export type GithubComComfyCreatorsCreatorBackendInternalDomainGenerationComfyWorkflow = { [key: string]: unknown };
