/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Forge Maestro API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */
import type { GithubComComfyCreatorsCreatorBackendInternalDomainBatchPriority } from './githubComComfyCreatorsCreatorBackendInternalDomainBatchPriority';
import type { GithubComComfyCreatorsCreatorBackendInternalDomainBatchStatus } from './githubComComfyCreatorsCreatorBackendInternalDomainBatchStatus';

export interface GithubComComfyCreatorsCreatorBackendInternalDomainBatch {
  completed_at?: string;
  completed_generations?: number;
  created_at?: string;
  failed_generations?: number;
  id?: string;
  priority?: GithubComComfyCreatorsCreatorBackendInternalDomainBatchPriority;
  status?: GithubComComfyCreatorsCreatorBackendInternalDomainBatchStatus;
  total_generations?: number;
  user_id?: string;
}
