/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Forge Maestro API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */
import type { GithubComComfyCreatorsCreatorBackendInternalClientMjolnirInstanceDetails } from './githubComComfyCreatorsCreatorBackendInternalClientMjolnirInstanceDetails';
import type { GithubComComfyCreatorsCreatorBackendInternalClientMjolnirInstanceType } from './githubComComfyCreatorsCreatorBackendInternalClientMjolnirInstanceType';

export interface GithubComComfyCreatorsCreatorBackendInternalClientMjolnirInstance {
  created_at?: string;
  details?: GithubComComfyCreatorsCreatorBackendInternalClientMjolnirInstanceDetails;
  id?: string;
  internal_ip?: string;
  location?: string;
  name?: string;
  network?: string;
  provider?: string;
  public_ip?: string;
  /** Should map to LeaseStatus */
  status?: string;
  tags?: string[];
  type?: GithubComComfyCreatorsCreatorBackendInternalClientMjolnirInstanceType;
}
