/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * ComfyUI Backend API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */

export interface GithubComComfyCreatorsCreatorBackendInternalDomainTeamWithMembership {
  archived_at?: string;
  created_at?: string;
  created_by_user_id?: string;
  id?: string;
  joined_at?: string;
  name?: string;
  role?: string;
  slug?: string;
  status?: string;
  updated_at?: string;
}
