/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Forge Maestro API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */
import type { GithubComComfyCreatorsCreatorBackendInternalDomainBatch } from './githubComComfyCreatorsCreatorBackendInternalDomainBatch';
import type { GithubComComfyCreatorsCreatorBackendInternalDomainGeneration } from './githubComComfyCreatorsCreatorBackendInternalDomainGeneration';

export interface InternalApiHandlerBatchResponse {
  batch?: GithubComComfyCreatorsCreatorBackendInternalDomainBatch;
  generations?: GithubComComfyCreatorsCreatorBackendInternalDomainGeneration[];
}
