/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Forge Maestro API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */
import type { GithubComComfyCreatorsCreatorBackendInternalDomainBatchPriority } from './githubComComfyCreatorsCreatorBackendInternalDomainBatchPriority';
import type { GithubComComfyCreatorsCreatorBackendInternalServiceGenerationGenerationInput } from './githubComComfyCreatorsCreatorBackendInternalServiceGenerationGenerationInput';

export interface InternalApiHandlerGenerateRequest {
  /** @minItems 1 */
  generations: GithubComComfyCreatorsCreatorBackendInternalServiceGenerationGenerationInput[];
  priority: GithubComComfyCreatorsCreatorBackendInternalDomainBatchPriority;
}
