/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Forge Maestro API
 * The core orchestrator backend for ComfyUI generation scaling.
 * OpenAPI spec version: 1.0
 */

export type PostApiV1AdminInstancesTerminateProviderParams = {
/**
 * Provider-side VM ID
 */
provider_vm_id: string;
/**
 * Provider name (e.g. vastai, datacrunch)
 */
provider: string;
};
